alias s='ls'

alias gs='git status'
alias ga='git add --all'
alias gad='git add'
alias gc='git commit -m'
alias gco='git checkout'
alias gcm='git commit'
alias gca='git commit --amend'
alias gq='git pull'
alias gk='git reset'
alias gkh='git reset --hard'
alias gkha='git reset --hard HEAD^'
alias gp='git push'
alias gg='git switch'
alias ggo='git switch -c'
alias grs='git restore --staged'
alias grc='git rm --cached'
alias gr='git restore'
alias gd='git diff'
alias gdc='git diff --cached'
alias gda='git diff HEAD^'
alias gm='git merge'
alias gl='git log'
alias gll='git log --graph --oneline --decorate'
alias gt='git stash'
alias gtp='git stash pop'
alias gcl='git clone'
alias gcl1='git clone --depth=1'
alias gsmu='git submodule update --init --recursive'

alias g='git'
alias p='python'
alias b='$EDITOR'
alias v='$PAGER'
